dist: trusty

language: php

php:
  - 7.1

before_install:
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY
  - composer create-project magento/magento-coding-standard --stability=dev magento-coding-standard

script:
  - magento-coding-standard/vendor/bin/phpcs --ignore=./vendor/*,./magento-coding-standard/*,./Test/* --standard=Magento2 --extensions=php,phtml,js .
